dependencies:
    - smartcontractkit/chainlink-brownie-contracts@1.1.1
    - OpenZeppelin/openzeppelin-contracts@3.4.0
compiler:
    solc:
        remappings:
            - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
            - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.0'
networks:
    default: development
    goerli: 
        vrf_coordinator: '0x2ca8e0c643bde4c2e08ab1fa0da3401adad7734d'
        eth_usd_price_feed: '0xD4a33860578De61DBAbDc8BFdb98FD742fA7028e'
    mainnet-fork:
        eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
wallets:
    from_keys: ${PRIVATE_KEY}


